name: ServerAlias
main: no.sonkin.serverAlias.ServerAlias
version: 1.0
author: Sonkin
commands:
  reloadutils:
    description: reload the config
    permission: bungeeutils.reload
permissions:
  bungeeutils.reload:
    description: Allows reloading
    default: false